"""Utility modules for data management, metrics, augmentation, and preprocessing."""

from utils.augmentation import (
    CIFAR10_MEAN,
    CIFAR10_STD,
    augment_cifar10_batch,
    create_cosine_schedule,
    normalize_cifar10,
)
from utils.data_processing import (
    DATASET_ALIASES,
    DATASET_CATALOG,
    DATASET_DEFAULT_CONFIGS,
    DATASET_TO_MODALITY,
    HF_MODERN_MIRRORS,
    DatasetPaths,
    clean_dataset_data,
    clean_modality_data,
    clean_processed_data,
    clean_raw_data,
    configure_hf_cache_dir,
    get_dataset_modality,
    get_federated_dataset,
    get_federated_dataset_from_parquet,
    get_project_root,
    list_supported_datasets,
    load_processed_dataset,
    prepare_and_save_dataset,
    prepare_modality_datasets,
    resolve_dataset_name,
)

__all__ = [
    "CIFAR10_MEAN",
    "CIFAR10_STD",
    "DATASET_ALIASES",
    "DATASET_CATALOG",
    "DATASET_DEFAULT_CONFIGS",
    "DATASET_TO_MODALITY",
    "DatasetPaths",
    "HF_MODERN_MIRRORS",
    "augment_cifar10_batch",
    "clean_dataset_data",
    "clean_modality_data",
    "clean_processed_data",
    "clean_raw_data",
    "configure_hf_cache_dir",
    "create_cosine_schedule",
    "get_dataset_modality",
    "get_federated_dataset",
    "get_federated_dataset_from_parquet",
    "get_project_root",
    "list_supported_datasets",
    "load_processed_dataset",
    "normalize_cifar10",
    "prepare_and_save_dataset",
    "prepare_modality_datasets",
    "resolve_dataset_name",
]
